#  use a exisitng image as base
#  mvn dependency:copy-dependencies -DoutputDirectory=./dependency

#mvn de.qaware.maven:go-offline-maven-plugin:1.1.0:resolve-dependencies -Dmaven.repo.local=.m2/repository
#mvn clean install -Dmaven.test.skip=true -Dtest=CheckBoxTest -Dmaven.repo.local=.m2/r


# to improve image so dependecy are not downladed all the time

#https://cbh.dev/going-offline-with-maven/

#mvn clean test -Dtest=SimpleFormDemoTest -Dselenide.browser="chrome" -Dselenide.isheadless=true

#docker run -it 1d0ceb5d5472 mvn clean test -Dtest=DockerTest


FROM maven:3.8-adoptopenjdk-8
RUN apt-get update
#RUN apt-get install vim -y

#selenium on chrome and headless possibilty of taking screen shot is there
RUN curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /chrome.deb
RUN dpkg -i /chrome.deb || apt-get install -yf
RUN rm /chrome.deb
#RUN sudo apt-get install libgconf-2-4

#RUN mvn clean
WORKDIR /usr/AutomationE2E
COPY ./pom.xml /usr/AutomationE2E
RUN mvn -B -f pom.xml -s /usr/share/maven/ref/settings-docker.xml dependency:resolve
RUN mvn -f pom.xml dependency:go-offline
COPY ./src /usr/AutomationE2E/src
COPY ./driver /usr/AutomationE2E/driver
COPY ./configs /usr/AutomationE2E/configs

RUN mvn clean test -Dtest=DockerTest


#dowmloaf and install a dependency if required
#VOLUME /usr/automation_fm/test

#tell the image what to do when it start
#as a contianer


CMD ["mvn","-o", "clean" ,"test" ,"-Dtest=CheckBoxTest" ,"-Dselenide.browser=chrome" ,"-Dselenide.isheadless=true"]



